### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# MacPorts Installer addition on 2012-11-22_at_23:55:19: adding an appropriate PATH variable for use with MacPorts.
export PATH=$PATH:/opt/local/bin:/opt/local/sbin
export PATH=/usr/local/bin:$PATH # Steam Games request
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH=$PATH:/Users/juarezlustosa/projects/influunt/influunt-app/node_modules/phantomjs/lib/phantom/bin
export PATH=$PATH:/Users/juarezlustosa/projects/influunt/influunt-app/node_modules/chromedriver/bin
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/
export PATH="$PATH:$JAVA_HOME:$HOME/activator/bin"
source $HOME/dotfiles/main/env
source $HOME/dotfiles/main/config
source $HOME/dotfiles/main/aliases

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
